import Head from 'next/head';
import Header from '@/components/Header';

import { roboto } from '@/utils/fonts';
import Hero from '@/components/Hero';
export default function Home() {
  return (
    <>
      <Head>
        <title>monblanproject</title>
        <meta name="description" content="Generated by monblanproject" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={` ${roboto.className}`}>
        <Header />
        <Hero />
      </main>
    </>
  );
}
